apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: golang-hello-world-develop
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "1800"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "1800"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
           name: golang-hello-world
           port:
             number: 8080
    host: demo.golang-hello-world.example.com