apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: golang-hello-world-istio
  labels:
    app: golang-hello-world
spec:
  gateways:
  - golang-hello-world
  hosts:
  - golang-hello-world.local
  - acme.com
  http:
  - name: primary
    route:
    - destination:
        host: golang-hello-world
        port:
          number: 8080
      weight: 100
    - destination:
        host: golang-hello-world-canary
        port:
          number: 8080
      weight: 0
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: golang-hello-world
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 8080
      name: http
      protocol: HTTP
    hosts:
     - "*"